package org.example.online_banking_system.model;


import jakarta.persistence.*;

@Entity  // specifies that the class is an entity and is mapped to a database table called accounts, by default the table could take the name of the class
@Table (name = "accounts")
public class Account {
    @Id // specifies the primary key of an entity
    @GeneratedValue (strategy = GenerationType.IDENTITY)
    /*
    * The @GeneratedValue annotation is used to specify how the primary key should be generated.
    * The strategy element defines the primary key generation strategy to be used. GenerationType.IDENTITY indicates
    * that the primary key value is automatically generated by the database when a new record is inserted into the table.
    * This typically relies on an auto-increment column in the database.*/
    @Column (name = "id", nullable = false)
    private Long id;
    @Column (nullable = false) //  indicates that the column must have a value; it cannot be NULL.
    private String accountNumber;

    @Column (nullable = false)
    private Double balance;

    @Column(nullable = false)
    private String accountType;


    // Constructors
    public Account() {
    }
    public Account(String accountNumber, Double balance) {
        this.accountNumber = accountNumber;
        this.balance = balance;
    }



    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

    public String getAccountType() {
        return accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }
}
